### ISSUE TITLE
Proxy are not been saved after they are checked

### ISSUE THREAD

**Issue by AnAverageBeing** [Z3NTL3/ProxyBeast#1]
![image](https://user-images.githubusercontent.com/84959276/212468599-d2bcfcf7-a2d6-4721-b751-9537bac5a330.png)

after checking when i cat the file i see no output

![image](https://user-images.githubusercontent.com/84959276/212468610-823e5aae-48db-48f7-8c39-398ae8d68d29.png)

got valid proxies but it didn't save them

**Comment by Z3NTL3** [comment]
Hey make sure to give the script 755 permissions

``chmod 755 executable``
will solve your issue!
