### ISSUE TITLE
Add new functionality

### ISSUE THREAD

**Issue by ctcomjo** [Z3NTL3/ProxyBeast#5]
Could you please add the functionality for ProxyBeast to check for the availability of proxies using the protocols HTTP, HTTPS, SOCKS4, and SOCKS5 in a single file?

**Comment by Z3NTL3** [comment]
Hello,

First of all, thanks for your enhancement push request.
As answer to your question: Yes, this will be implemented soon.

Our way of implementing this into ProxyBeast:
Normally the option flag ``-protocol`` is a required arg flag to provide, but if you provide ``-all true`` it'll abandon ``-protocol`` flag. The ``-all`` flag will be false as default, so you require to define it explicitly.

So if you set this flag explicitly the proxy checker will generate proxy-saves txt files in ``saves`` dir respectively.  For example for an socks4 proxy -> ``saves/goods-socks4.txt`` and so on...
This way ProxyBeast can provide multiple proxy protocol checking.

Note:  If this flag is not set, the default proxy checking functionality as known will be used by the program.

**Comment by AnAverageBeing** [comment]
yes that's a good idea
